Name:           ros-indigo-sr-ronex
Version:        0.9.15
Release:        0%{?dist}
Summary:        ROS sr_ronex package

Group:          Development/Libraries
License:        LGPLv3
URL:            http://www.shadowrobot.com/products/ronex
Source0:        %{name}-%{version}.tar.gz

BuildArch:      noarch

Requires:       ros-indigo-sr-ronex-controllers
Requires:       ros-indigo-sr-ronex-drivers
Requires:       ros-indigo-sr-ronex-examples
Requires:       ros-indigo-sr-ronex-external-protocol
Requires:       ros-indigo-sr-ronex-hardware-interface
Requires:       ros-indigo-sr-ronex-launch
Requires:       ros-indigo-sr-ronex-msgs
Requires:       ros-indigo-sr-ronex-transmissions
Requires:       ros-indigo-sr-ronex-utilities
BuildRequires:  ros-indigo-catkin

%description
This stack contains the different packages related to the RoNeX (Robot Nervous
System).

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
mkdir -p build && cd build
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/indigo" \
        -DCMAKE_PREFIX_PATH="/opt/ros/indigo" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
cd build
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/indigo

%changelog
* Sun Dec 21 2014 Shadow Robot's software team <software@shadowrobot.com> - 0.9.15-0
- Autogenerated by Bloom

